default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ac_chat_development

test: &test
  <<: *default
  database: ac_chat_test

production:
  <<: *default
  database: ac_chat_production
  username: ac_chat
  password: <%= ENV['PAY_WALL_DEMO_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
